language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - libxml2-utils
    - oracle-java8-installer
    - oracle-java8-set-default
before_install:
- source ./src/ci/before_install.sh
install:
- "true"
script:
- "./src/ci/build.sh"
after_success:
  - bash <(curl -s https://codecov.io/bash) -f okta-spring-security-starter/target/site/jacoco/jacoco.xml

after_failure:
  - find integration-tests/oauth2/target/failsafe-reports/ -type f | xargs -I{} sh -c 'echo {}; cat {}'

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_API_KEY
    local_dir: target/gh-pages
    email: developers@okta.com
    name: Travis CI - Auto Doc Build
    on:
      branch: master